ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    
    # 좌표계 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # 바퀴 데이터 (속도 정보 위주)
    odom0: /odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]

    # IMU 데이터 (회전 정보 위주)
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,  # Yaw(회전각)만 사용
                  false, false, false,
                  false, false, true,  # 회전 속도 사용
                  false, false, false] # 가속도는 진동 때문에 무시(False)